spring:
  application:
    name: testApp

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/demo
    username: sa
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.practice.spring.echo