spring:
  application:
    name: echoModule
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/sla
    username: sa
    password:
#  jpa:
#    hibernate:
#      ddl-auto: create

  plea:
    name: jykim
    height: 178
